
```{r} 
install.packages('htmltab')
library(htmltab)
```
```{r}
install.packages('tidyr')
library(tidyr)
```
```{r}
install.packages('stringr')
library(stringr)
```
```{r}
install.packages('rio')
library(rio)
```
```{r}
lkpage='https://www.cia.gov/library/publications/resources/the-world-factbook/fields/361.html'
lkpath='//*[@id="fieldListing"]'
```
```{r}
'agua potable' = htmltab(doc = lkpage, which = lkpath)
```
```{r}
names(`agua potable`)
```
```{r}
`agua potable`=separate(`agua potable`,"Drinking water source",into=c('z1','z2','z3','z4'), 'population')
```
```{r}
`agua potable`$z1=NULL
`agua potable`$z2=NULL
`agua potable`$z4=NULL
```
```{r} 
`agua potable`$z3=str_extract_all(`agua potable`$z3,pattern="(\\-*\\d+\\.*\\d*)")
```
```{r} 
`agua potable`$z3=as.numeric(`agua potable`$z3)
```
```{r}
str(`agua potable`)
```
```{r}
names(`agua potable`)=c('Pais','% of population with access to improved drinking water')
```
```{r}
lkpaises='https://github.com/GonzaloBerger/covid-19/raw/master/lista_de_paises.xlsx'
```
```{r}
datapaises=import(lkpaises)
```
```{r}
Aguapotable=merge(datapaises,`agua potable`)
```