
```{r}
install.packages('rio')
library(rio)
```
```{r}
lkcorrup='https://github.com/GonzaloBerger/123/raw/master/Data_Extract_From_Worldwide_Governance_control_of_corruption.xlsx'
```
```{r}
datacorrup=import(lkcorrup)
```
```{r}
datacorrup[c(2:4)]=NULL
```
```{r}
datacorrup=datacorrup[c(1:99),]
```
```{r}
names(datacorrup)=c('Pais','Control de la corrupcion')
```
```{r}
str(datacorrup)
```
```{r}
datacorrup$`Control de la corrupcion`=as.numeric(datacorrup$`Control de la corrupcion`)
```
```{r}
lkviolence='https://github.com/GonzaloBerger/123/raw/master/Data_Extract_From_Worldwide_Governance_Indicators_political_stability_and_absence_of_violence.xlsx'
```
```{r}
dataviolence=import(lkviolence)
```
```{r}
dataviolence[c(2:4)]=NULL
```
```{r}
dataviolence=dataviolence[c(1:99),]
```
```{r}
names(dataviolence)=c('Pais','Estabilidad politica y ausencia de violencia/terrorismo')
```
```{r}
str(dataviolence)
``` 
```{r}
dataviolence$`Estabilidad politica y ausencia de violencia/terrorismo`=as.numeric(dataviolence$`Estabilidad politica y ausencia de violencia/terrorismo`)
```
```{r}
corrupcion_y_violencia=merge(datacorrup,dataviolence)
```
```{r}
lkpaises='https://github.com/GonzaloBerger/covid-19/raw/master/lista_de_paises.xlsx'
```
```{r}
datapaises=import(lkpaises)
```
```{r}
Corrupcion_y_violencia=merge(datapaises,corrupcion_y_violencia)
```